#!/bin/sh -x

# reviewer-added --change <change id> --change-url <change url> --project <project name> --branch <branch> --reviewer <reviewer> 

logfile=/home/gerrit/review/reviewer-added.log

echo date: $(date) >> ${logfile}
echo reviewer-added $* >> ${logfile}

while test -n "$1"; do
  case $1 in
    --change)
      change=$2;
      shift 2;;
    --project)
      project=$2;
      shift 2;;
    --branch)
      branch=$2;
      shift 2;;
    --reviewer)
      reviewer=$2;
      shift 2;;
    *)
      shift 1;;
  esac
done

if [[ "${reviewer}" =~ '郭春茂（管理员）' ]]; then
  echo "set-reviewers -p ${project} ${change} --add isxxguo --remove cmguo" >> ${logfile}
  ssh checker gerrit set-reviewers -p ${project} ${change} --add isxxguo
fi

echo "------------------------------------------------" >> ${logfile}
